from linkedlist import LinkedList

my_ll = LinkedList(4)
my_ll.append(5)
my_ll.append(6)
my_ll.append(7)

# print(my_ll.head.value)
# print(my_ll.tail.value)
# print(my_ll.get(2))
print("before")
my_ll.print_linkedlist()
print(my_ll.revert())
print("after")
my_ll.print_linkedlist()
# print("before pop first")
# my_ll.pop_first()
# my_ll.print_linkedlist()
# print("before pop second")
# my_ll.pop_first()
# my_ll.print_linkedlist()
# print("before")
# my_ll.print_linkedlist()
# print("after")
# my_ll.pop()
# print("after1")
# my_ll.print_linkedlist()
# my_ll.pop()
# print("after2")
# my_ll.print_linkedlist()
# my_ll.pop()
# print("after3")
# my_ll.print_linkedlist()
# my_ll.pop()
# print("after4")
# my_ll.print_linkedlist()

# my_ll.prepend(100)
# print("after prepend")
# my_ll.print_linkedlist()

